export enum ErrorCode {
  // Authentication
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',

  // Series
  SERIES_NOT_FOUND = 'SERIES_NOT_FOUND',
  SERIES_NOT_PUBLISHED = 'SERIES_NOT_PUBLISHED',
  SERIES_PROBABILITY_INVALID = 'SERIES_PROBABILITY_INVALID',

  // Figure
  FIGURE_NOT_FOUND = 'FIGURE_NOT_FOUND',

  // Purchase
  PURCHASE_PAYMENT_FAILED = 'PURCHASE_PAYMENT_FAILED',
  PURCHASE_INSUFFICIENT_STOCK = 'PURCHASE_INSUFFICIENT_STOCK',
  PURCHASE_ORDER_NOT_FOUND = 'PURCHASE_ORDER_NOT_FOUND',

  // Voucher
  VOUCHER_NOT_FOUND = 'VOUCHER_NOT_FOUND',
  VOUCHER_EXPIRED = 'VOUCHER_EXPIRED',
  VOUCHER_ALREADY_REDEEMED = 'VOUCHER_ALREADY_REDEEMED',
  VOUCHER_INVALID_TOKEN = 'VOUCHER_INVALID_TOKEN',
  VOUCHER_ALREADY_EXTENDED = 'VOUCHER_ALREADY_EXTENDED',

  // Branch
  BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',
  BRANCH_INACTIVE = 'BRANCH_INACTIVE',

  // Stock
  STOCK_INSUFFICIENT = 'STOCK_INSUFFICIENT',
  STOCK_TRANSFER_INVALID = 'STOCK_TRANSFER_INVALID',

  // Drop Events
  DROP_NOT_FOUND = 'DROP_NOT_FOUND',
  DROP_NOT_ACTIVE = 'DROP_NOT_ACTIVE',
  DROP_SOLD_OUT = 'DROP_SOLD_OUT',
  DROP_LIMIT_EXCEEDED = 'DROP_LIMIT_EXCEEDED',
  DROP_EARLY_ACCESS_DENIED = 'DROP_EARLY_ACCESS_DENIED',

  // Referral
  REFERRAL_CODE_INVALID = 'REFERRAL_CODE_INVALID',
  REFERRAL_SELF_REFER = 'REFERRAL_SELF_REFER',

  // Generic
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}
